language: python
sudo: false

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - curl https://raw.githubusercontent.com/dmerejkowsky/dmenv/master/installer.py -o dmenv-installer.py
  - python3 dmenv-installer.py --dest ./dmenv
  - ./dmenv install

script:
  - bash ci.sh
