language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv check
  - pipenv run pyflakes ui/__init__.py ui/tests/test_ui.py
  - pipenv run pytest
  - pipenv run sphinx-build -W docs docs/_build/html
