name: doc-check
on: [push]

jobs:
  check_doc:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install and configure poetry
      run: |
        python -m pip install poetry
        python -m poetry config virtualenvs.create false

    - name: Prepare project for development
      run: python -m poetry install

    - name: Check doc builds without warnings
      run: |
        poetry run sphinx-build -W docs docs/_build/html



