name: doc-deploy
on:
  push:
    branches:
      master

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dmenv
      uses: TankerHQ/dmenv-install-action@v1.0.0
      with:
        dmenv-version: 0.20.0

    - name: Prepare project for development
      run: dmenv install

    - name: Build documentation
      run: |
        dmenv install
        dmenv run -- sphinx-build -W docs docs/_build/html

    - name: Deploy to GitHub pages
      uses: maxheld83/ghpages@v0.1.1
      env:
        BUILD_DIR: docs/_build/html
        GH_PAT: ${{ secrets.GH_PAT }}



