name: linters

on: [push]

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install and configure poetry
      run: |
        python -m pip install poetry
        python -m poetry config virtualenvs.create false

    - name: Prepare project for development
      run: python -m poetry install

    - name: Run black
      run: |
        python -m poetry run black --check .

    - name: Run mypy
      run: |
        MYPYPATH=stubs python -m poetry run mypy --ignore-missing-imports --strict cli_ui

    - name: Run pyflakes
      run: |
        python -m poetry run pyflakes cli_ui/__init__.py cli_ui/tests/test_cli_ui.py


