name: linters

on: [push]

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dmenv
      uses: TankerHQ/dmenv-install-action@v1.0.0
      with:
        dmenv-version: 0.20.0

    - name: Prepare project for development
      run: dmenv install

    - name: Run black
      run: |
        dmenv run -- black --check .

    - name: Run mypy
      run: |
        MYPYPATH=stubs dmenv run -- mypy --ignore-missing-imports --strict cli_ui

    - name: Run pyflakes
      run: |
        dmenv run -- pyflakes cli_ui/__init__.py cli_ui/tests/test_cli_ui.py


